sudo: false

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install .[testing]
# CBC dependancies
  - sudo apt-get update
  - sudo apt-get -y install coinor-libcbc-dev
  - pip install cylp

script:
    - pytest tests/

notifications:
  email: false
