name: PyGammaAgreement
dependencies:
  - python>=3.6
  - cython>=0.20.1
  - numpy>=1.10.4
  - numpydoc
  - mock
  - pandas>=0.17.0
  - pip
  - pytest>=2.6
  - pytest-cov
  - scipy>=1.1
  - setuptools
  - sphinx_rtd_theme
  - pip
  - pip:
    - h5features>=1.3
    - h5py>=2.3.0
    - pyannote-core >=3.0
    - jupyter
